//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBookingDemo.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class TravelRequestDetail
    {
        public int RequestId { get; set; }
        [Required(ErrorMessage ="Employee Id Required")]
        public Nullable<int> EmpId { get; set; }
        [Required(ErrorMessage = "Manager Id Required")]
        public Nullable<int> EmpMgrId { get; set; }
        [Required(ErrorMessage = " Required")]
        public string TravelSource { get; set; }
        [Required(ErrorMessage = "Required")]
        public string TravelDestination { get; set; }
        [Required(ErrorMessage = "Purpose Required")]
        public string Purpose { get; set; }
        [Required(ErrorMessage = "Required")]
        public System.DateTime DepartureDate { get; set; }
        [Required(ErrorMessage = "Required")]
        public System.DateTime ReturnDate { get; set; }
        [Required(ErrorMessage = "Required")]
        public string TravelMode { get; set; }
        public string ManagerStatus { get; set; }
        public string AgentStatus { get; set; }
        public string CostInvolved { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Manager Manager { get; set; }
        public bool ReadyForBooking { get;  set; }
        public string RejectionReason { get; set; }
    }
}
