//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBookingDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TravelAgent
    {
        public int AgentId { get; set; }
        [Required(ErrorMessage ="Name Is Required !!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email Is Required !!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phone Number Is Required !!")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Agency Id is Required !!")]
        public int Agencyid { get; set; }
        [Required(ErrorMessage = "Agency Password Is Required !!")]
        public string AgentPassword { get; set; }
    }
}
